[package]
name = "colink-protocol-s3h"
version = "0.1.3"
edition = "2021"
default-run = "colink-protocol-s3h"

[dependencies]
colink = "0.2.0"
ctrlc = "3.2"
regex = "1.6"
serde_json = "1.0"
structopt = "0.3"
tokio = "1.18"
tracing = "0.1"
url = "2.2"
uuid = { version = "0.8", features = ["v4"] }
