on:
  release:
    types: [released]

name: Build

env:
  PROTOCOL_NAME: s3h
  PACKAGE_NAME: colink-protocol-s3h

jobs:
  build:
    uses: CoLearn-Dev/colink-protocol-inventory-workflow-templates/.github/workflows/rust.yml@main
    with:
      protocol_name: s3h
      package_name: colink-protocol-s3h
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
